-- Add new fields to people table
ALTER TABLE people
ADD COLUMN IF NOT EXISTS maiden_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS birth_place VARCHAR(255),
ADD COLUMN IF NOT EXISTS death_date DATE,
ADD COLUMN IF NOT EXISTS death_place VARCHAR(255),
ADD COLUMN IF NOT EXISTS marriage_place VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN DEFAULT FALSE;
